
import type { Ticket } from "@/types/ticket";

export const initialTickets: Ticket[] = [
  {
    id: "ticket-001",
    externalId: "EXT-1001",
    customerName: "Aarav Sharma",
    customerEmail: "aarav@example.com",
    subject: "Unable to log in",
    description: "I cannot access my account after resetting my password.",
    status: "open",
    priority: "P1",
    category: "Account",
    assignedTo: "Unassigned",
    createdAt: "2026-09-30T09:30:00.000Z",
  },
  {
    id: "ticket-002",
    externalId: "EXT-1002",
    customerName: "Priya Das",
    customerEmail: "priya@example.com",
    subject: "Payment not reflecting",
    description: "My payment was successful, but the dashboard still shows it as pending.",
    status: "in_progress",
    priority: "P2",
    category: "Billing",
    assignedTo: "Riya",
    createdAt: "2026-09-29T11:15:00.000Z",
  },
  {
    id: "ticket-003",
    externalId: "EXT-1003",
    customerName: "Rahul Roy",
    customerEmail: "rahul@example.com",
    subject: "Need help updating profile",
    description: "I want to change the phone number linked to my account.",
    status: "pending",
    priority: "P3",
    category: "Account",
    assignedTo: "Amit",
    createdAt: "2026-09-28T14:45:00.000Z",
  },
  {
    id: "ticket-004",
    externalId: "EXT-1004",
    customerName: "Sneha Gupta",
    customerEmail: "sneha@example.com",
    subject: "App keeps crashing",
    description: "The application closes whenever I open the reports page.",
    status: "open",
    priority: "P1",
    category: "Technical",
    assignedTo: "Unassigned",
    createdAt: "2026-09-27T08:00:00.000Z",
  },
  {
    id: "ticket-005",
    externalId: "EXT-1005",
    customerName: "Neha Singh",
    customerEmail: "neha@example.com",
    subject: "Refund status",
    description: "Could you please provide an update on my refund?",
    status: "resolved",
    priority: "P4",
    category: "Billing",
    assignedTo: "Riya",
    createdAt: "2026-09-26T16:20:00.000Z",
  },
];